---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicast-demo
  labels:
    app: multicast-demo
  annotations:
    flux.weave.works/locked_user: ilya <ilya@weave.works>
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"dev"'
spec:
  replicas: 12
  selector:
    matchLabels:
      app: multicast-demo
  template:
    metadata:
      labels:
        app: multicast-demo
    spec:
      containers:
      - name: multicast-demo
        image: weaveworksdemos/multicast:b7111cb
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
