apiVersion: skaffold/v1alpha2
kind: Config

## Default profile for use with `skaffold dev`
build:
  artifacts:
  - imageName: weaveworksdemos/multicast
    docker:
      dockerfilePath: ./Dockerfile
deploy:
  kubectl: { manifests: [ config/prod/deployment.yaml ] }

